### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by spiliti** [Sunbird-RC/community#155]
### What is the bug related to?

Registry CLI

### What went wrong?

When I ran 'registry help', I get the following error:

/home/shuller/.nvm/versions/node/v6.17.1/lib/node_modules/registry-cli/out/src/cli.js:14
async function run(argv) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/shuller/.nvm/versions/node/v6.17.1/lib/node_modules/registry-cli/bin/registry:13:2)

### What did you expect to see?

I should have seen commands to use with the registry

**Comment by gamemaker1** [comment]
Hi @spiliti,

It looks like you are using Node v6.17.1. The Registry CLI needs a minimum of Node 8 because it uses async-await. However, using the latest version of Node (v16.13.0) is recommended.

From the logs, I understand you are using NVM to manage NodeJS versions. Here is the command you can run to switch to the latest version:

```
nvm use lts
```

Let me know if you need any help.

**Comment by spiliti** [comment]
Registry Setup

Thanks. Now when I try to initialize a registry (/example$ registry init) I get the following feedback: 

✔ All necessary tools installed!

✔ Enter the name of the registry · Example
✔ Enter the name of the Keycloak realm to create · sunbird-rc
✔ Enter the ID to assign to the admin client in Keycloak · admin-api
✔ Enter the ID to assign to the frontend client in Keycloak · registry-frontend
✔ Enter a username for the admin account in Keycloak · admin
✔ Enter a password for the admin account in Keycloak · admin
✔ Enter the path to a directory containing entity schemas · use-example-config
✔ Enter the path to a file containing consent configuration · use-example-config

✔ Successfully copied over necessary files
✖ An unexpected error occurred while starting the registry: Command failed with exit code 125: docker compose up -d

**Comment by spiliti** [comment]
Below is my docker-compose.yaml. I quess I have to upgrade docker-compose .
version: '2.4'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'localhost:9200/_cluster/health']
      interval: 30s
      timeout: 10s
      retries: 4
    ports:
      - '9200:9200'
      - '9300:9300'
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  rg:
    image: dockerhub/sunbird-rc-core
    volumes:
      - ./config/schemas:/home/opensaber/config/public/_schemas
    environment:
      - connectionInfo_uri=jdbc:postgresql://db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
      - elastic_search_connection_url=es:9200
      - search_provider=io.opensaber.registry.service.ElasticSearchService
      - sunbird_sso_realm=sunbird-rc
      - sunbird_sso_url=http://kc:8080/auth
      - sunbird_sso_admin_client_id=admin-api
      - sunbird_sso_client_id=registry-frontend
      - sunbird_sso_admin_client_secret=INSERT_SECRET_HERE
      - claims_url=http://cs:8082
    ports:
      - '8081:8081'
    depends_on:
      es:
        condition: service_healthy
      db:
        condition: service_started
      kc:
        condition: service_healthy
  kc:
    image: dockerhub/ndear-keycloak
    volumes:
      - ./config/keycloak:/opt/jboss/keycloak/imports
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=registry
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9990/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '8080:8080'
      - '9990:9990'
    depends_on:
      db:
        condition: service_started
  cs:
    image: dockerhub/open-saber-claim-ms
    environment:
      - connectionInfo_uri=jdbc:postgresql://db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
      - opensaber_url=http://rg:8081
    ports:
      - '8082:8082'
    depends_on:
      db:
        condition: service_started
      rg:
        condition: service_started

**Comment by gamemaker1** [comment]
// Answering in #164
