### ISSUE TITLE
[BUG]: Unable to start ndear-keycloak using docker

### ISSUE THREAD

**Issue by ChakshuGautam** [Sunbird-RC/community#187]
### What is the bug related to?

Registry Core

### What went wrong?

`docker-compose up -d` on `kc` fails after stalling for 2-3 mins on M1 mac with default docker desktop. Initial setup was done using registry-cli.

Sharing the stack trace here.
```sh
kc_1  | Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
kc_1  |
kc_1  | =========================================================================
kc_1  |
kc_1  |   Using PostgreSQL database
kc_1  |
kc_1  | =========================================================================
kc_1  |
kc_1  | 04:54:13,283 INFO  [org.jboss.modules] (CLI command executor) JBoss Modules version 1.11.0.Final
kc_1  | 04:54:13,617 INFO  [org.jboss.msc] (CLI command executor) JBoss MSC version 1.4.12.Final
kc_1  | 04:54:13,648 INFO  [org.jboss.threads] (CLI command executor) JBoss Threads version 2.4.0.Final
kc_1  | 04:54:14,091 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) starting
kc_1  | 04:54:14,575 INFO  [org.jboss.vfs] (MSC service thread 1-5) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
kc_1  | 04:54:17,554 INFO  [org.wildfly.security] (ServerService Thread Pool -- 20) ELY00001: WildFly Elytron version 1.15.3.Final
kc_1  | 04:54:19,692 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 22) WFLYCTL0033: Extension 'security' is deprecated and may not be supported in future versions
kc_1  | 04:54:22,550 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
kc_1  | 04:54:23,868 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
kc_1  | 04:54:24,805 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-1) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Used blank.
kc_1  | 04:54:24,846 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-5) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
kc_1  | WARNING: An illegal reflective access operation has occurred
kc_1  | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-15.0.1.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
kc_1  | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
kc_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
kc_1  | WARNING: All illegal access operations will be denied in a future release
kc_1  | 04:54:25,098 INFO  [org.jboss.as.patching] (MSC service thread 1-5) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
kc_1  | 04:54:25,196 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-4) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
kc_1  | 04:54:25,839 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
kc_1  | 04:54:25,849 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) started in 12502ms - Started 59 of 82 services (32 services are lazy, passive or on-demand)
kc_1  | The batch executed successfully
kc_1  | 04:54:26,759 INFO  [org.jboss.as] (MSC service thread 1-5) WFLYSRV0050: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) stopped in 75ms
kc_1  | 04:54:35,771 INFO  [org.jboss.modules] (CLI command executor) JBoss Modules version 1.11.0.Final
kc_1  | 04:54:36,065 INFO  [org.jboss.msc] (CLI command executor) JBoss MSC version 1.4.12.Final
kc_1  | 04:54:36,094 INFO  [org.jboss.threads] (CLI command executor) JBoss Threads version 2.4.0.Final
kc_1  | 04:54:36,584 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) starting
kc_1  | 04:54:37,037 INFO  [org.jboss.vfs] (MSC service thread 1-5) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
kc_1  | 04:54:40,472 INFO  [org.wildfly.security] (ServerService Thread Pool -- 22) ELY00001: WildFly Elytron version 1.15.3.Final
kc_1  | 04:54:42,603 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 14) WFLYCTL0033: Extension 'security' is deprecated and may not be supported in future versions
kc_1  | 04:54:44,442 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
kc_1  | 04:54:45,017 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
kc_1  | 04:54:45,912 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-1) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Used blank.
kc_1  | 04:54:45,957 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-3) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
kc_1  | WARNING: An illegal reflective access operation has occurred
kc_1  | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-15.0.1.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
kc_1  | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
kc_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
kc_1  | WARNING: All illegal access operations will be denied in a future release
kc_1  | 04:54:46,171 INFO  [org.jboss.as.patching] (MSC service thread 1-4) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
kc_1  | 04:54:46,842 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-4) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
kc_1  | 04:54:47,398 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
kc_1  | 04:54:47,416 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) started in 11593ms - Started 59 of 89 services (39 services are lazy, passive or on-demand)
kc_1  | The batch executed successfully
kc_1  | 04:54:48,588 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) stopped in 112ms
kc_1  | =========================================================================
kc_1  |
kc_1  |   JBoss Bootstrap Environment
kc_1  |
kc_1  |   JBOSS_HOME: /opt/jboss/keycloak
kc_1  |
kc_1  |   JAVA: java
kc_1  |
kc_1  |   JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true   --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED
kc_1  |
kc_1  | =========================================================================
kc_1  |
kc_1  | 04:54:54,154 INFO  [org.jboss.modules] (main) JBoss Modules version 1.11.0.Final
kc_1  | 04:54:56,368 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.12.Final
kc_1  | 04:54:56,399 INFO  [org.jboss.threads] (main) JBoss Threads version 2.4.0.Final
kc_1  | 04:54:56,790 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) starting
kc_1  | 04:54:57,814 INFO  [org.jboss.vfs] (MSC service thread 1-2) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
kc_1  | 04:55:00,718 INFO  [org.wildfly.security] (ServerService Thread Pool -- 22) ELY00001: WildFly Elytron version 1.15.3.Final
kc_1  | 04:55:02,186 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 13) WFLYCTL0033: Extension 'security' is deprecated and may not be supported in future versions
kc_1  | 04:55:04,095 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
kc_1  | 04:55:04,380 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 23) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
kc_1  | 04:55:05,453 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
kc_1  | 04:55:05,572 INFO  [org.xnio] (MSC service thread 1-1) XNIO version 3.8.4.Final
kc_1  | 04:55:05,630 INFO  [org.xnio.nio] (MSC service thread 1-1) XNIO NIO Implementation Version 3.8.4.Final
kc_1  | 04:55:05,659 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service org.wildfly.network.interface.public: org.jboss.msc.service.StartException in service org.wildfly.network.interface.public: WFLYSRV0082: failed to resolve interface public
kc_1  | 	at org.jboss.as.server@15.0.1.Final//org.jboss.as.server.services.net.NetworkInterfaceService.start(NetworkInterfaceService.java:98)
kc_1  | 	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
kc_1  | 	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
kc_1  | 	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
kc_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
kc_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
kc_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
kc_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
kc_1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
kc_1  |
kc_1  | 04:55:05,910 INFO  [org.wildfly.extension.health] (ServerService Thread Pool -- 38) WFLYHEALTH0001: Activating Base Health Subsystem
kc_1  | 04:55:05,913 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 39) WFLYCLINF0001: Activating Infinispan subsystem.
kc_1  | 04:55:05,925 INFO  [org.jboss.as.clustering.jgroups] (ServerService Thread Pool -- 43) WFLYCLJG0001: Activating JGroups subsystem. JGroups version 4.2.11
kc_1  | 04:55:05,995 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 55) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments running multiple servers. Please make sure the attribute value is unique.
kc_1  | 04:55:06,033 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 53) WFLYSEC0002: Activating Security Subsystem
kc_1  | 04:55:06,033 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 50) WFLYNAM0001: Activating Naming Subsystem
kc_1  | 04:55:06,087 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 40) WFLYIO001: Worker 'default' has auto-configured to 6 IO threads with 48 max task threads based on your 3 available processors
kc_1  | 04:55:06,077 INFO  [org.jboss.as.connector] (MSC service thread 1-4) WFLYJCA0009: Starting Jakarta Connectors Subsystem (WildFly/IronJacamar 1.4.27.Final)
kc_1  | 04:55:06,152 INFO  [org.wildfly.extension.metrics] (ServerService Thread Pool -- 48) WFLYMETRICS0001: Activating Base Metrics Subsystem
kc_1  | 04:55:06,150 INFO  [org.jboss.remoting] (MSC service thread 1-2) JBoss Remoting version 5.0.20.Final
kc_1  | 04:55:06,303 INFO  [org.jboss.as.security] (MSC service thread 1-1) WFLYSEC0001: Current PicketBox version=5.0.3.Final-redhat-00007
kc_1  | 04:55:06,576 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 33) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
kc_1  | 04:55:06,712 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 41) WFLYRS0016: RESTEasy version 3.15.1.Final
kc_1  | 04:55:06,731 INFO  [org.jboss.as.naming] (MSC service thread 1-3) WFLYNAM0003: Starting Naming Service
kc_1  | 04:55:06,914 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0003: Undertow 2.2.5.Final starting
kc_1  | 04:55:06,941 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 33) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 42.2)
kc_1  | 04:55:07,150 WARN  [org.wildfly.clustering.web.undertow] (ServerService Thread Pool -- 56) WFLYCLWEBUT0007: No routing provider found for default-server; using legacy provider based on static configuration
kc_1  | 04:55:07,291 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-5) WFLYJCA0018: Started Driver service with driver-name = h2
kc_1  | 04:55:07,378 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-4) WFLYJCA0018: Started Driver service with driver-name = postgresql
kc_1  | 04:55:07,802 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-3) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
kc_1  | 04:55:08,344 INFO  [org.jboss.as.ejb3] (MSC service thread 1-3) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 12 (per class), which is derived from the number of CPUs on this host.
kc_1  | 04:55:08,345 INFO  [org.jboss.as.ejb3] (MSC service thread 1-4) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 48 (per class), which is derived from thread worker pool sizing.
kc_1  | 04:55:08,420 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 56) WFLYUT0014: Creating file handler for path '/opt/jboss/keycloak/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
kc_1  | 04:55:09,014 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-3) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Used blank.
kc_1  | 04:55:09,261 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-3) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
kc_1  | 04:55:09,291 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0012: Started server default-server.
kc_1  | WARNING: An illegal reflective access operation has occurred
kc_1  | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-15.0.1.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
kc_1  | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
kc_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
kc_1  | WARNING: All illegal access operations will be denied in a future release
kc_1  | 04:55:09,339 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) Queuing requests.
kc_1  | 04:55:09,343 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0018: Host default-host starting
kc_1  | 04:55:11,144 INFO  [org.jboss.as.patching] (MSC service thread 1-2) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
kc_1  | 04:55:11,225 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-4) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
kc_1  | 04:55:11,263 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-1) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/keycloak/standalone/deployments
kc_1  | 04:55:11,328 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
kc_1  | 04:55:12,029 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
kc_1  |     ("core-service" => "management"),
kc_1  |     ("management-interface" => "http-interface")
kc_1  | ]) - failure description: {
kc_1  |     "WFLYCTL0412: Required services that are not installed:" => ["jboss.http-upgrade-registry.http-management"],
kc_1  |     "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.remoting.remoting-http-upgrade-service.http-management is missing [jboss.http-upgrade-registry.http-management]"]
kc_1  | }
kc_1  | 04:55:12,040 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("interface" => "public")]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.network.interface.public" => "WFLYSRV0082: failed to resolve interface public"}}
kc_1  | 04:55:12,044 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
kc_1  |     ("subsystem" => "remoting"),
kc_1  |     ("http-connector" => "http-remoting-connector")
kc_1  | ]) - failure description: {
kc_1  |     "WFLYCTL0412: Required services that are not installed:" => ["jboss.http-upgrade-registry.default"],
kc_1  |     "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.remoting.remoting-http-upgrade-service.http-remoting-connector is missing [jboss.http-upgrade-registry.default]"]
kc_1  | }
kc_1  | 04:55:12,046 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "keycloak-server.war")]) - failure description: {
kc_1  |     "WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.transactions.global-default-local-provider"],
kc_1  |     "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.deployment.unit.\"keycloak-server.war\".REGISTER is missing [org.wildfly.transactions.global-default-local-provider]"]
kc_1  | }
kc_1  | 04:55:12,337 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "jca")]) - failure description: {
kc_1  |     "WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.transactions.global-default-local-provider"],
kc_1  |     "WFLYCTL0180: Services with missing/unavailable dependencies" => ["org.wildfly.jca.transaction-integration is missing [org.wildfly.transactions.global-default-local-provider]"]
kc_1  | }
kc_1  | 04:55:12,343 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
kc_1  |     ("subsystem" => "ejb3"),
kc_1  |     ("service" => "timer-service"),
kc_1  |     ("file-data-store" => "default-file-store")
kc_1  | ]) - failure description: {
kc_1  |     "WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.transactions.global-default-local-provider"],
kc_1  |     "WFLYCTL0180: Services with missing/unavailable dependencies" => ["org.wildfly.ejb3.timer-service.timer-persistence-service.default-file-store is missing [org.wildfly.transactions.global-default-local-provider]"]
kc_1  | }
kc_1  | 04:55:12,351 ERROR [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0459: Triggering roll back due to missing management services.
kc_1  | 04:55:12,352 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
kc_1  |     ("core-service" => "management"),
kc_1  |     ("management-interface" => "http-interface")
kc_1  | ]) - failure description: {
kc_1  |     "WFLYCTL0412: Required services that are not installed:" => ["jboss.http-upgrade-registry.http-management"],
kc_1  |     "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.remoting.remoting-http-upgrade-service.http-management is missing [jboss.http-upgrade-registry.http-management]"]
kc_1  | }
kc_1  | 04:55:12,408 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0028: Stopped deployment keycloak-server.war (runtime-name: keycloak-server.war) in 39ms
kc_1  | 04:55:12,473 ERROR [org.jboss.as.server] (ServerService Thread Pool -- 46) WFLYSRV0021: Deploy of deployment "keycloak-server.war" was rolled back with the following failure message:
kc_1  | {
kc_1  |     "WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.transactions.global-default-local-provider"],
kc_1  |     "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.deployment.unit.\"keycloak-server.war\".REGISTER is missing [org.wildfly.transactions.global-default-local-provider]"]
kc_1  | }
kc_1  | 04:55:12,554 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-2) WFLYMAIL0002: Unbound mail session [java:jboss/mail/Default]
kc_1  | 04:55:12,553 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0019: Stopped Driver service with driver-name = postgresql
kc_1  | 04:55:12,566 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-6) WFLYJCA0019: Stopped Driver service with driver-name = h2
kc_1  | 04:55:12,592 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0019: Host default-host stopping
kc_1  | 04:55:12,607 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0004: Undertow 2.2.5.Final stoppin
kc_1  | 04:55:12,973 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
kc_1  | 04:55:13,046 INFO  [org.jboss.as] (MSC service thread 1-4) WFLYSRV0050: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) stopped in 44ms
kc_1  | deploy_kc_1 exited with code 1
```

### What did you expect to see?

Should see the server running fine. I was not able to find any meaningful information tagged to M1 either.

**Comment by gamemaker1** [comment]
This issue seems to be related to a bad `/etc/hosts` file - could you please paste your `/etc/hosts`?

**Comment by ChakshuGautam** [comment]
Sharing the hosts file here
```
255.255.255.255	broadcasthost
::1 localhost
127.0.0.1 kubernetes.docker.internal localhost ts.air.server air.server
165.232.182.146 dev-kafka
11.2.6.6 sunbird-dev
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by gamemaker1** [comment]
Could you please try removing the duplicate `127.0.0.1 kubernetes.docker.internal` line at the end? It's already mentioned in the third line.

**Comment by ChakshuGautam** [comment]
Same issue.

**Comment by ChakshuGautam** [comment]
Tried restarting the docker after hosts file update as well.
