### ISSUE TITLE
[BUG]: Search operation of a Schema with "anonymous" manage role is failing

### ISSUE THREAD

**Issue by saiprakash-v** [Sunbird-RC/community#303]
### What is the bug related to?

Registry Core

### What went wrong?

I have created a schema with `roles` property set to `["anonymous"]`. When a search query is made for this entity, I'm getting `403 forbidden` error. 

### What did you expect to see?

Should have returned an array of entries to the corresponding entity

### Additional Context

After going through source code, 
In the version 11 release, after the new filter was added to bypass authentication of anonymous schema https://github.com/Sunbird-RC/sunbird-rc-core/pull/173 , user principal doesn't get generated.
So, this https://github.com/Sunbird-RC/sunbird-rc-core/blob/6f7c0d3943a027e70ec1a9dd4878d2f415968b6b/java/registry/src/main/java/dev/sunbirdrc/registry/helper/RegistryHelper.java#L727 is throwing forbidden error

### Relevant logs/output (if any)

```shell
Error stack trace:
`at dev.sunbirdrc.registry.helper.RegistryHelper.getKeycloakUserId(RegistryHelper.java:731) 
 at dev.sunbirdrc.registry.helper.RegistryHelper.fetchUserIdFromToken(RegistryHelper.java:723)
at dev.sunbirdrc.registry.helper.RegistryHelper.getUserId(RegistryHelper.java:713)
at dev.sunbirdrc.registry.helper.RegistryHelper.getUserInfoFromRegistry(RegistryHelper.java:775)
at dev.sunbirdrc.registry.helper.RegistryHelper.getRequestedUserDetails(RegistryHelper.java:752)
at dev.sunbirdrc.registry.controller.RegistryEntityController.getEntityByToken(RegistryEntityController.java:563)`
```

**Comment by tejash-jl** [comment]
@saiprakash-v why are you not using `/search` API? 
I think you are using GET `api/v1/<Schema/`, this requires a valid token to return the entries.

**Comment by saiprakash-v** [comment]
So, the search api doesn't require any token right? Will try using that going forward. Are there any differences in the results by using either of them?

Irrespective of that, I'm assuming that this still needs to be fixed right?

**Comment by tejash-jl** [comment]
Search API will return only the public fields. It also supports filters & pagination.
